server:
  port: 84


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.104:8848  #nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080  #sentinel地址
        port: 8719

service-url:
  nacos-user-service: http://nacos-payment-provider

