server:
  port: 8002


spring:
  application:
    name: cloud-payment-service #项目名字，入驻到eurekaServer时，就是用的这个名字入驻的
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://172.16.8.199:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12345Asdfg
    druid:
      test-while-idle: false #解决 durid启动时报testWhileIdle is true, validationQuery not set，意思是校验没有设置，将testWhiledle修改为false，不再报错。

eureka:
  client:
    register-with-eureka: true #表示 是否将自己注册进EurekaServer ，默认为true。如果是false，则表示不注册进EurekaServer
    fetch-registry: true  #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true  #访问路径可以显示IP地址

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities  #所有Entitiy别名类所在包




