server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名字
  client:
    register-with-eureka: false #表识不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #表示向eurekaServer7001进行注册 #设置与eureka server交互的地址查询服务和注册服务都需. ${eureka.instance.hostname} 表示上面的localhost ，${server.port}表示7上面的001端口

