server:
  port: 3344
spring:
  application:
    name: cloud-config-center  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/lixianSharp/sprincloud-config.git  #GitHub上面的git仓库名字
          ###搜索目录(对应上面的git仓库中的目录名)
          search-paths:
          - springcloud-config
      ##读取分支
      label: master

  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    host: 172.16.8.11
    username: guest
    password: guest
    port: 5672

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'



